# Generated by Django 5.2.15 on 2026-08-13 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, verbose_name='Número do ano')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Ano',
                'verbose_name_plural': 'Anos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dificuldade', models.CharField(blank=True, choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], max_length=10)),
                ('tempo_estimado', models.CharField(blank=True, max_length=40, verbose_name='Tempo estimado')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('pre_requisitos', models.TextField(blank=True)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Programar publicação')),
                ('prazo_recomendado', models.DateField(blank=True, null=True, verbose_name='Prazo recomendado')),
                ('fixada', models.BooleanField(default=False, verbose_name='Fixar atividade')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('arquivada', 'Arquivada')], default='rascunho', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='core.ano')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-fixada', '-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos/%Y/%m/', verbose_name='Arquivo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome de exibição')),
                ('tipo_arquivo', models.CharField(blank=True, max_length=10, verbose_name='Extensão')),
                ('tamanho', models.PositiveBigIntegerField(default=0, verbose_name='Tamanho em bytes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.atividade', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('heading', 'Título'), ('markdown', 'Markdown'), ('code', 'Código'), ('terminal', 'Terminal'), ('image', 'Imagem'), ('gallery', 'Galeria'), ('video', 'Vídeo'), ('embed', 'Embed'), ('list', 'Lista'), ('steps', 'Passo a Passo'), ('checklist', 'Checklista'), ('table', 'Tabela'), ('quote', 'Citação'), ('alert', 'Aviso'), ('link', 'Link'), ('links', 'Links Externos'), ('file', 'Download'), ('accordion', 'Acordeão'), ('divider', 'Divisor'), ('question', 'Questão')], max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('dados', models.JSONField(default=dict)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='core.atividade')),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Ícone (@mdi)')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.ano')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['ano', 'nome'],
                'unique_together': {('ano', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='core.disciplina'),
        ),
    ]
