# Generated by Django 5.2.17 on 2026-09-16 20:59

import uploader.helpers.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(storage=uploader.helpers.storage.raw_storage, upload_to='arquivos/%Y/%m/', verbose_name='Arquivo'),
        ),
    ]
