# Generated by Django 5.2.17 on 2026-09-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_arquivo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='capa',
            field=models.URLField(blank=True, max_length=500, verbose_name='Imagem de capa'),
        ),
    ]
