# Generated by Django 5.2.17 on 2026-09-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_atividade_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='categoria',
            field=models.CharField(choices=[('questao', 'Questão'), ('atividade', 'Atividade'), ('tutorial', 'Tutorial')], default='atividade', max_length=10, verbose_name='Categoria'),
        ),
    ]
