# Generated by Django 5.2.17 on 2026-09-16 20:59

import uploader.helpers.storage
import uploader.models.document
import uploader.models.video
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_key', models.UUIDField(default=uuid.uuid4, help_text='Used to attach the video to another object. Cannot be used to retrieve the video file.', unique=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, help_text='Used to retrieve the video file itself. Should not be readable until the video is attached to another object.', unique=True)),
                ('file', models.FileField(storage=uploader.helpers.storage.video_storage, upload_to=uploader.models.video.video_file_path)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=uploader.helpers.storage.raw_storage, upload_to=uploader.models.document.document_file_path),
        ),
    ]
